BB Point Bots Update
bots-business/BBPointBot pull request #10
Opened 2021-07-11 13:07 UTC by sohamdeogaonkar

2021-07-12 04:17 UTC, bots-business requested changes

2021-07-12 04:17 UTC, bots-business commented on commands/_setAngryPoints.js
> +var AngryPointsdata = AdminPanel.getPanel("AngryPoints")
please rename this to angryPointsPanel

2021-07-12 04:17 UTC, bots-business commented on commands/_setAngryPoints.js
> +var AngryPointsdata = AdminPanel.getPanel("AngryPoints")
from AngryPointsdata

2021-07-12 04:17 UTC, bots-business commented on commands/Transfering/transfer.js
> +  var angryPointsLimit = Libs.ResourcesLib.userRes("angryPointsLimit")
angryPointsLimit - I think it still not good name

angryPointsMaxLimit - is more good

2021-07-12 04:17 UTC, bots-business commented on commands/Transfering/transfer.js
> +  var angryPoints = Libs.ResourcesLib.userRes("angryPoints")
angryPointsHourlyLimit - please rename. It is Hourly limit

2021-07-13 09:47 UTC, sohamdeogaonkar commented
![image](https://user-images.githubusercontent.com/63729589/125430807-b76e34b1-2137-4c36-86f7-7987443ddc08.png)

2021-07-13 11:18 UTC, sohamdeogaonkar commented
@bots-business ?

2021-07-14 05:29 UTC, bots-business requested changes

2021-07-14 05:29 UTC, bots-business commented on commands/Transfering/transfer.js
> +  var angryPoints = Libs.ResourcesLib.userRes("angryPoints")
avaibleAngryPoints - please rename it

2021-07-14 05:29 UTC, bots-business commented on commands/_setAngryPoints.js
> +angryPointsPanel.fields[0].value = ""
I think we do not need this clearing

2021-07-14 05:30 UTC, bots-business requested changes
need changes

2021-07-14 05:31 UTC, closed without merging