BB Point Bot Update
bots-business/BBPointBot pull request #6
Opened 2021-06-20 11:06 UTC by sohamdeogaonkar

2021-06-20 11:40 UTC, sohamdeogaonkar commented
@bots-business  ?

2021-06-21 02:07 UTC, bots-business requested changes

2021-06-21 02:07 UTC, bots-business commented on commands/@.js
> +function canMasterRemove(value){
please format code

2021-06-21 02:07 UTC, bots-business commented on commands/@.js
> +function canMasterRemove(value){
need format all code

2021-06-21 02:07 UTC, closed without merging